"""
Send a Resend email when an unreacted EU defense contract-win opportunity is detected.
"""
from __future__ import annotations

import html
import os
from typing import Any

import requests

RESEND_URL = "https://api.resend.com/emails"
TIMEOUT = 30


def send_alert(
    *,
    ticker: str,
    company_name: str,
    country: str,
    buyer_name: str,
    notice_title: str,
    contract_value_native: float | None,
    contract_currency: str | None,
    contract_value_usd: int | None,
    predicted_pct: float,
    actual_pct: float,
    confidence: str,
    materiality: str,
    rationale: str,
    baseline_close: float,
    baseline_date: str,
    current_price: float,
    notice_url: str,
    publication_date: str,
) -> dict[str, Any]:
    api_key = os.environ["RESEND_API_KEY"]
    to_addr = os.environ["NOTIFY_EMAIL_TO"]
    from_addr = os.environ.get(
        "NOTIFY_EMAIL_FROM", "Contract Routine <onboarding@resend.dev>"
    )

    gap = predicted_pct - actual_pct
    if contract_value_native is not None and contract_currency:
        native_str = f"{contract_value_native:,.0f} {contract_currency}"
    else:
        native_str = "undisclosed"
    usd_str = f"~${contract_value_usd:,}" if contract_value_usd else "n/a"

    subject = (
        f"[EU Defense Alert] {ticker} unreacted — "
        f"predicted {predicted_pct:+.2f}% vs actual {actual_pct:+.2f}%"
    )

    body_html = f"""<!doctype html>
<html><body style="font-family: -apple-system, system-ui, sans-serif; max-width: 720px;">
<h2 style="margin:0 0 8px 0;">EU Defense Contract-Win Alert — {ticker}</h2>
<p style="margin:0 0 16px 0;"><strong>{html.escape(company_name)}</strong> · {html.escape(country)} · TED published {publication_date}</p>

<h3>Prediction vs Reaction</h3>
<table cellpadding="6" cellspacing="0" border="1" style="border-collapse:collapse; font-family:monospace;">
  <tr><td>Predicted move</td><td><strong>{predicted_pct:+.2f}%</strong></td></tr>
  <tr><td>Actual move (so far)</td><td><strong>{actual_pct:+.2f}%</strong></td></tr>
  <tr><td>Unreacted gap</td><td><strong>{gap:+.2f}%</strong></td></tr>
  <tr><td>Baseline close ({baseline_date})</td><td>{baseline_close:.2f}</td></tr>
  <tr><td>Current price</td><td>{current_price:.2f}</td></tr>
  <tr><td>Contract value (native)</td><td>{native_str}</td></tr>
  <tr><td>Contract value (USD)</td><td>{usd_str}</td></tr>
  <tr><td>Buyer</td><td>{html.escape(buyer_name)}</td></tr>
  <tr><td>Confidence</td><td>{html.escape(confidence)}</td></tr>
  <tr><td>Materiality</td><td>{html.escape(materiality)}</td></tr>
</table>

<h3>LLM Rationale</h3>
<p>{html.escape(rationale)}</p>

<h3>Notice</h3>
<p>{html.escape(notice_title)}</p>

<p><a href="{html.escape(notice_url)}">TED notice (EN)</a></p>

<hr/>
<p style="color:#888; font-size:12px;">Generated by contract-win-eu-defense routine.</p>
</body></html>"""

    r = requests.post(
        RESEND_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "from": from_addr,
            "to": [to_addr],
            "subject": subject,
            "html": body_html,
        },
        timeout=TIMEOUT,
    )
    r.raise_for_status()
    return r.json()
