"""
Shared Resend email helper for contract-monitor-* skills.

Triggered when |predicted_pct| > threshold (default 3%). Subject distinguishes
NEW vs UPDATE so the inbox tells you whether the contract is fresh or a material
modification to a known award.
"""
from __future__ import annotations

import html
import os
from typing import Any

import requests

RESEND_URL = "https://api.resend.com/emails"
TIMEOUT = 30


def send_alert(
    *,
    source_name: str,
    event_type: str,  # "new" or "update"
    ticker: str,
    company_name: str,
    sector: str,
    country: str,
    contract_value_usd: int,
    contract_id: str,
    paragraph: str,
    predicted_pct: float,
    confidence: str,
    materiality: str,
    rationale: str,
    model: str,
    source_url: str,
    announcement_date: str,
    last_modified_date: str,
    quote: dict[str, Any] | None,
    update_context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    api_key = os.environ["RESEND_API_KEY"]
    to_addr = os.environ["NOTIFY_EMAIL_TO"]
    from_addr = os.environ.get(
        "NOTIFY_EMAIL_FROM", "Contract Routine <onboarding@resend.dev>"
    )

    tag = "NEW" if event_type == "new" else "UPDATE"
    subject = (
        f"[Contract {tag} · {sector}] {ticker} — predicted {predicted_pct:+.2f}% "
        f"({source_name})"
    )

    quote_html = ""
    if quote:
        cur = quote.get("currency") or ""
        quote_html = f"""
<tr><td>Current price</td><td>{quote['current_price']:.2f} {html.escape(cur)}</td></tr>
<tr><td>Prior close ({html.escape(quote['prior_date'])})</td><td>{quote['prior_close']:.2f} {html.escape(cur)}</td></tr>"""

    update_html = ""
    if event_type == "update" and update_context:
        prior_amt = update_context.get("prior_amount_usd")
        delta = update_context.get("amount_delta_pct")
        prior_lm = update_context.get("prior_last_modified")
        update_html = f"""
<h3>Update Context</h3>
<table cellpadding="6" cellspacing="0" border="1" style="border-collapse:collapse; font-family:monospace;">
  <tr><td>Prior amount</td><td>${prior_amt:,}</td></tr>
  <tr><td>Amount delta</td><td>{delta:+.1f}%</td></tr>
  <tr><td>Previously last-modified</td><td>{html.escape(prior_lm or 'n/a')}</td></tr>
</table>"""

    body_html = f"""<!doctype html>
<html><body style="font-family: -apple-system, system-ui, sans-serif; max-width: 720px;">
<h2 style="margin:0 0 4px 0;">Contract {tag} Alert — {ticker} ({html.escape(sector)})</h2>
<p style="margin:0 0 12px 0;"><strong>{html.escape(company_name)}</strong> · {html.escape(country)}</p>
<p style="margin:0 0 12px 0; font-size:13px; color:#555;">
  Source: {html.escape(source_name)}<br/>
  Announced / award date: {html.escape(announcement_date)}<br/>
  Last modified: {html.escape(last_modified_date)}
</p>

<h3>Prediction</h3>
<table cellpadding="6" cellspacing="0" border="1" style="border-collapse:collapse; font-family:monospace;">
  <tr><td>Predicted next-session move</td><td><strong>{predicted_pct:+.2f}%</strong></td></tr>
  <tr><td>Confidence</td><td>{html.escape(confidence)}</td></tr>
  <tr><td>Materiality</td><td>{html.escape(materiality)}</td></tr>
  <tr><td>Contract value</td><td>${contract_value_usd:,}</td></tr>
  <tr><td>Contract / award ID</td><td>{html.escape(contract_id)}</td></tr>
  <tr><td>LLM model</td><td>{html.escape(model)}</td></tr>{quote_html}
</table>

<h3>LLM Rationale</h3>
<p>{html.escape(rationale)}</p>
{update_html}
<h3>Contract Text</h3>
<pre style="white-space: pre-wrap; background:#f5f5f5; padding:12px; border-radius:6px; font-size:13px;">{html.escape(paragraph)}</pre>

<p><a href="{html.escape(source_url)}">Source notice</a></p>

<hr/>
<p style="color:#888; font-size:12px;">Generated by contract-monitor-{html.escape(source_name.lower())}. Public-procurement data can lag the actual press release / 8-K. Cross-check the company's IR newsroom before trading.</p>
</body></html>"""

    r = requests.post(
        RESEND_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "from": from_addr,
            "to": [to_addr],
            "subject": subject,
            "html": body_html,
        },
        timeout=TIMEOUT,
    )
    r.raise_for_status()
    return r.json()
