"""
Resend email helper for the pharma-regulatory-monitor skill. Triggered when
|predicted_pct| > 2.0%. Subject indicates the regulatory source and event type
so the inbox tells you at a glance whether it's an approval, recall, or
trial-status change.
"""
from __future__ import annotations

import html
import os
from typing import Any

import requests

RESEND_URL = "https://api.resend.com/emails"
TIMEOUT = 30

SOURCE_PRETTY = {
    "FDA": "FDA",
    "ClinicalTrials.gov": "CT.gov",
    "EMA": "EMA",
}

EVENT_TAG = {
    "fda_approval": "APPROVAL",
    "fda_tentative_approval": "TENTATIVE APPROVAL",
    "fda_recall": "RECALL",
    "trial_status_change": "TRIAL",
    "ema_news": "EMA NEWS",
}


def send_alert(
    *,
    source_name: str,
    hit: dict[str, Any],
    predicted_pct: float,
    confidence: str,
    materiality: str,
    rationale: str,
    model: str,
    quote: dict[str, Any] | None,
) -> dict[str, Any]:
    api_key = os.environ["RESEND_API_KEY"]
    to_addr = os.environ["NOTIFY_EMAIL_TO"]
    from_addr = os.environ.get(
        "NOTIFY_EMAIL_FROM", "Pharma Reg Monitor <onboarding@resend.dev>"
    )

    ticker = hit.get("ticker", "")
    company_name = hit.get("company_name", "")
    country = hit.get("country", "")
    sector = hit.get("sector", "Pharma")
    event_type = hit.get("event_type", "unknown")
    event_subtype = hit.get("event_subtype", "")
    headline = hit.get("headline", "")
    paragraph = hit.get("paragraph", "")
    source_url = hit.get("source_url", "")
    announcement_date = hit.get("announcement_date", "")
    last_modified_date = hit.get("last_modified_date", "")

    src_pretty = SOURCE_PRETTY.get(source_name, source_name)
    tag = EVENT_TAG.get(event_type, event_type.upper())
    subject = (
        f"[Pharma · {tag}] {ticker} — predicted {predicted_pct:+.2f}% "
        f"({src_pretty})"
    )

    quote_html = ""
    if quote:
        cur = quote.get("currency") or ""
        quote_html = f"""
<tr><td>Current price</td><td>{quote['current_price']:.2f} {html.escape(cur)}</td></tr>
<tr><td>Prior close ({html.escape(quote['prior_date'])})</td><td>{quote['prior_close']:.2f} {html.escape(cur)}</td></tr>"""

    body_html = f"""<!doctype html>
<html><body style="font-family: -apple-system, system-ui, sans-serif; max-width: 720px;">
<h2 style="margin:0 0 4px 0;">Pharma Regulatory Alert — {html.escape(ticker)} ({html.escape(sector)})</h2>
<p style="margin:0 0 12px 0;"><strong>{html.escape(company_name)}</strong> · {html.escape(country)}</p>
<p style="margin:0 0 12px 0; font-size:13px; color:#555;">
  Source: {html.escape(source_name)}<br/>
  Event: {html.escape(event_type)} ({html.escape(event_subtype)})<br/>
  Announced / event date: {html.escape(announcement_date)}<br/>
  Last modified: {html.escape(last_modified_date)}
</p>

<h3 style="margin-bottom:4px;">Headline</h3>
<p style="margin-top:0;">{html.escape(headline)}</p>

<h3>Prediction</h3>
<table cellpadding="6" cellspacing="0" border="1" style="border-collapse:collapse; font-family:monospace;">
  <tr><td>Predicted next-session move</td><td><strong>{predicted_pct:+.2f}%</strong></td></tr>
  <tr><td>Confidence</td><td>{html.escape(confidence)}</td></tr>
  <tr><td>Materiality</td><td>{html.escape(materiality)}</td></tr>
  <tr><td>LLM model</td><td>{html.escape(model)}</td></tr>{quote_html}
</table>

<h3>LLM Rationale</h3>
<p>{html.escape(rationale)}</p>

<h3>Event Text</h3>
<pre style="white-space: pre-wrap; background:#f5f5f5; padding:12px; border-radius:6px; font-size:13px;">{html.escape(paragraph)}</pre>

<p><a href="{html.escape(source_url)}">Source page</a></p>

<hr/>
<p style="color:#888; font-size:12px;">Generated by pharma-regulatory-monitor. Public regulatory feeds occasionally lag the company's own press release / 8-K; cross-check the company IR newsroom before trading.</p>
</body></html>"""

    r = requests.post(
        RESEND_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "from": from_addr,
            "to": [to_addr],
            "subject": subject,
            "html": body_html,
        },
        timeout=TIMEOUT,
    )
    r.raise_for_status()
    return r.json()
